// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcyyhoikoofgsgqrxzet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjeXlob2lrb29mZ3NncXJ4emV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTY5NjUsImV4cCI6MjA3MzUzMjk2NX0.VHWWNU8o1-G-4S5D2V-dMUb31rKhQF2ebxPN_LwbLiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});